### ISSUE TITLE
Minor suggestions

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/plan-generator#1]
Hi Xiaoran, 
just a few minor suggestions - sorted by tab. 
(Sorry for not posting them as individual issues). 
Cheers 

# General comments
- Would be good if clicking "replace" would update without need for "undo". 
- I think H2020 has changed to "Horizon Europe" with an adapted DMP template (https://ec.europa.eu/info/funding-tenders/opportunities/docs/2021-2027/horizon/temp-form/report/data-management-plan-template_he_en.docx)
- Some of the EU is hardcoded. It's terribly much work, but I would suggest to add options for e.g. DFG, ERC, BMBF 

# Tab: General information 
- Maybe increase text boxes for study object & project aim 
- If I uncheck "Yes! I will use DataPlant.", the options below pop up under number "5.a". And not all are selectable.  
- Might make sense to explain (or link) the endpoint choices as people might ot know them. 

# Tab: Data type
- I think the choices picked here do not affect the text 

# Tab: Data volume
- Since the helper text says "in GiB", add unit GB to the number in the text. 

# Tab: Relevant standards
- See above. Maybe link the (metadata) standards 
- Point 4.2: How early is early? 
- Point on IP is not selectable

**Comment by xiaoranzhou** [comment]
Hi Dominik, 

Thanks for your feedback.
The DMP generator is only for functioning test proposes. It just desmostrate the features and still under construction.
Here are some answers to your question.
I will probably grey out the checkboxes without a counterpart in the text.

# General comments
- Would be good if clicking "replace" would update without need for "undo". 
    - I would still keep the undo button, but I can also make the replace button do the undo first as well. 
- I think H2020 has changed to "Horizon Europe" with an adapted DMP template (https://ec.europa.eu/info/funding-tenders/opportunities/docs/2021-2027/horizon/temp-form/report/data-management-plan-template_he_en.docx)
    - Thanks for the link.
- Some of the EU is hardcoded. It's terribly much work, but I would suggest to add options for e.g. DFG, ERC, BMBF 
    - I don't understand what you mean.
# Tab: General information 
- Maybe increase text boxes for study object & project aim 
- If I uncheck "Yes! I will use DataPlant.", the options below pop up under number "5.a". And not all are selectable.  
    -Because there is a (no #if in text). The non-DataPLANT users is of course not our priority ;P  
- Might make sense to explain (or link) the endpoint choices as people might ot know them. 
    - Yes, just not now.

# Tab: Data type
- I think the choices picked here do not affect the text 
    - Some options are just mock ups, *RNAseq* , *other NGS (genomics)*,  *metabolomics* , *proteomics* those four is working

# Tab: Data volume
- Since the helper text says "in GiB", add unit GB to the number in the text. 
    - In the future we will add a function to help users to identify the size of their data.
# Tab: Relevant standards
- See above. Maybe link the (metadata) standards 
    - Here is high level standards, I will add some tips to the text.
- Point 4.2: How early is early? 
    -  Some tips can be added.
- Point on IP is not selectable 
    -  Yes, because there is no matching part in the text

As long as the text is improved, then more options will be added.
